id = "oxk"
name = "ArkTS"
description = "ArkTS language support for Zed with tree-sitter highlighting, formatting, and lint diagnostics."
version = "0.1.0"
schema_version = 1
authors = ["richerfu"]
repository = "https://github.com/harmony-contrib/oxk-zed"

[grammars.arkts]
repository = "https://github.com/harmony-contrib/tree-sitter-arkts"
rev = "3a6dd89c121c9ace24cc3642d62985d083145941"

[language_servers.arkts-language-server]
name = "ArkTS Language Server"
language = "ArkTS"

[language_servers.arkts-language-server.language_ids]
"ArkTS" = "ets"

[language_servers.oxk-formatter]
name = "Oxk Formatter"
language = "ArkTS"
languages = [
  "ArkTS",
  "JavaScript",
  "JSX",
  "TypeScript",
  "TSX",
  "Vue.js",
  "JSON",
  "JSON5",
  "JSONC",
  "HTML",
  "CSS",
  "SCSS",
  "LESS",
  "Angular",
  "GraphQL",
  "Handlebars",
  "Markdown",
  "MDX",
  "YAML",
  "TOML",
]

[language_servers.oxk-formatter.language_ids]
"Angular" = "angular"
"ArkTS" = "ets"
"CSS" = "css"
"GraphQL" = "graphql"
"HTML" = "html"
"Handlebars" = "handlebars"
"JSON" = "json"
"JSON5" = "json5"
"JSONC" = "jsonc"
"JSX" = "javascriptreact"
"JavaScript" = "javascript"
"LESS" = "less"
"MDX" = "mdx"
"Markdown" = "markdown"
"SCSS" = "scss"
"TOML" = "toml"
"TSX" = "typescriptreact"
"TypeScript" = "typescript"
"Vue.js" = "vue"
"YAML" = "yaml"

[language_servers.oxk-linter]
name = "Oxk Linter"
language = "ArkTS"

[language_servers.oxk-linter.language_ids]
"ArkTS" = "ets"
